# This file contains the values obtained by the calibration package
# Results are written in the form that they can be directly sent to a static_transform_publisher node
# Recall its usage use static_transform_publisher x y z qx qy qz qw frame_id child_frame_id  period(milliseconds)
translation: [0.0598756, 0.579741, 0.318738]
rotation: [0.613371, 0.613071, -0.351398, 0.352759]
frame_id: camera_rgb_optical_frame
child_frame_id: world
