# This file contains the values obtained by the calibration package
# Results are written in the form that they can be directly sent to a static_transform_publisher node
# Recall its usage use static_transform_publisher x y z qx qy qz qw frame_id child_frame_id  period(milliseconds)
translation: [0.136817, 0.19418, 1.18244]
rotation: [-0.34813, -0.6085, 0.622326, -0.348201]
frame_id: camera1_color_optical_frame
child_frame_id: panda_link0
