# This file contains the values obtained by the calibration package
# Results are written in the form that they can be directly sent to a static_transform_publisher node
# Recall its usage use static_transform_publisher x y z qx qy qz qw frame_id child_frame_id  period(milliseconds)
translation: [0.604045, -0.140561, 0.581927]
rotation: [0.0140163, 0.994172, -0.106288, -0.0113488]
frame_id: camera_color_optical_frame
child_frame_id: setup1/panda_link0
