# This file contains the values obtained by the calibration package
# Results are written in the form that they can be directly sent to a static_transform_publisher node
# Recall its usage use static_transform_publisher x y z qx qy qz qw frame_id child_frame_id  period(milliseconds)
translation: [-0.294391, 0.0413828, 0.761804]
rotation: [0.831455, -0.167864, 0.0830355, 0.523078]
frame_id: camera_color_optical_frame
child_frame_id: setup1/panda_link0
