# This file contains the values obtained by the calibration package
# Results are written in the form that they can be directly sent to a static_transform_publisher node
# Recall its usage use static_transform_publisher x y z qx qy qz qw frame_id child_frame_id  period(milliseconds)
translation: [-0.112663, -0.564751, 0.768387]
rotation: [0.718022, 0.689806, -0.0675995, 0.0635712]
frame_id: camera_color_optical_frame
child_frame_id: setup1/base
