# This file contains the values obtained by the calibration package
# Results are written in the form that they can be directly sent to a static_transform_publisher node
# Recall its usage use static_transform_publisher x y z qx qy qz qw frame_id child_frame_id  period(milliseconds)
translation: [0.0449162, -0.607472, 0.531857]
rotation: [0.699228, 0.714319, -0.0190416, 0.0215936]
frame_id: camera_color_optical_frame
child_frame_id: setup1/panda_link0
