# This file contains the values obtained by the calibration package
# Results are written in the form that they can be directly sent to a static_transform_publisher node
# Recall its usage use static_transform_publisher x y z qx qy qz qw frame_id child_frame_id  period(milliseconds)
translation: [-0.0662217, -0.819591, 1.05866]
rotation: [0.710562, 0.699433, -0.0527178, 0.0558212]
frame_id: zivid_optical_frame
child_frame_id: setup1/base
